version: '3.7'

services:
  explorer-dev:
    hostname: explorer-dev
    container_name: explorer-dev
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
      args:
        PORT: 4000
        MIX_ENV: ${MIX_ENV}
        NETWORK: ${NETWORK}
        SUBNETWORK: ${SUBNETWORK}
        COIN: ${COIN}
        ETHEREUM_JSONRPC_VARIANT: ${ETHEREUM_JSONRPC_VARIANT}
        ETHEREUM_JSONRPC_HTTP_URL: ${ETHEREUM_JSONRPC_HTTP_URL}
        ETHEREUM_JSONRPC_WS_URL: ${ETHEREUM_JSONRPC_WS_URL}
        DATABASE_URL: ${DATABASE_URL}
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
        GECCEX_APP_ID: ${GECCEX_APP_ID}
        GECCEX_CODE: ${GECCEX_CODE}
    ports:
      - 4000:4000
