version: '3.7'

services:
  explorer-mainnet:
    image: gojoychain/explorer-mainnet:2.1.0
    build:
      context: ../../
      dockerfile: ./docker/mainnet/Dockerfile
      args:
        PORT: 5000
        MIX_ENV: ${MIX_ENV}
        NETWORK: ${NETWORK}
        SUBNETWORK: ${SUBNETWORK}
        COIN: ${COIN}
        ETHEREUM_JSONRPC_VARIANT: ${ETHEREUM_JSONRPC_VARIANT}
        ETHEREUM_JSONRPC_HTTP_URL: ${ETHEREUM_JSONRPC_HTTP_URL}
        ETHEREUM_JSONRPC_WS_URL: ${ETHEREUM_JSONRPC_WS_URL}
        DATABASE_URL: ${DATABASE_URL}
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
        GECCEX_APP_ID: ${GECCEX_APP_ID}
        GECCEX_CODE: ${GECCEX_CODE}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      start_period: 10s
    ports:
      - 5000:5000
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"
